global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus scraper'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: ['produtos-app-instance:8080', 'usuarios-app-instance:8081', 'vendas-app-instance:8082']